### ISSUE TITLE
Error when content type missing

### ISSUE THREAD

**Issue by dpwrussell** [RDFLib/sparqlwrapper#100]
A recent change in the code added the type to the warning:

https://github.com/RDFLib/sparqlwrapper/blame/fa150179c11d1c2e496f134a96457bdbfd20deab/SPARQLWrapper/Wrapper.py#L878

but if the `if` statement (https://github.com/RDFLib/sparqlwrapper/blame/fa150179c11d1c2e496f134a96457bdbfd20deab/SPARQLWrapper/Wrapper.py#L850) is false, then the user will get:

```
  File "/Users/dpwrussell/.virtualenvs/sparql/lib/python2.7/site-packages/SPARQLWrapper/Wrapper.py", line 878, in convert
    warnings.warn("unknown response content type '%s' returning raw response..." %(ct), RuntimeWarning)
UnboundLocalError: local variable 'ct' referenced before assignment
```

I got this when I tried to convert results from an update operation, which doesn't make a lot of sense, but obviously it would be preferable to get a more pertinent error.

**Comment by dayures** [comment]
@dpwrussell thanks for the report!
