### ISSUE TITLE
Need Help for SPAQLWrapper

### ISSUE THREAD

**Issue by apurbapaul** [RDFLib/sparqlwrapper#101]
Hi,
I am a newbie in SPARQL. I want to explore all the SPARQL queries using SPARQLWRAPPER. I found online documentation. But it is not helpful for me. Currently, I am using SPARQL ebook. 
It will be an immense help for me if anybody will come forward and explain the details, at least some basic instruction about the wrapper.

**Comment by dayures** [comment]
Dear @apurbapaul ,

You can find the latest documentation of SPARQLWrapper at https://rdflib.github.io/sparqlwrapper/doc/latest/

BTW, this is an issue tracker, so I am going to close it, as it is not the best place for this kind of questions.
