### ISSUE TITLE
Using SPARQLWrapper.setTimeout() sets the global socket timeout

### ISSUE THREAD

**Issue by borntyping** [RDFLib/sparqlwrapper#106]
If you use `SPARQLWrapper.setTimeout()` the timeout argument is used to set the global socket timeout ([Wrapper.py#L759-L760](https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L759-L760)) instead of the timeout for requests made with SPARQLWrapper. This means that requests made from a different instance of SPARQLWrapper, or sockets in entirely separate code will may unexpectedly timeout.

I'm not sure if it's the case on earlier version of Python, but on 2.6 the `urlopen` function used  on [Wrapper.py#L764](https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L764) accepts a timeout argument, which would only apply to the requests made from that SPARQLWrapper instance.

**Comment by dayures** [comment]
fixed in 3dd4d468674ca9767b93ae33f2a3cff3a916c42d

**Comment by borntyping** [comment]
Thanks so much!
