### ISSUE TITLE
formats RDF, RDF-XML, TURTLE not properly working

### ISSUE THREAD

**Issue by steffres** [RDFLib/sparqlwrapper#107]
Hi all,

we are using your sparqlwrapper extensively but ran into problems regarding different return-formats which I couldn't resolve on my own. 

We run the following script

```
from SPARQLWrapper import *

sparql_endpoint = "http://dbpedia.org/sparql"
query = "select distinct ?Concept where {[] a ?Concept} LIMIT 10"

sparql_wrapper = SPARQLWrapper(sparql_endpoint)
sparql_wrapper.setQuery(query)
sparql_wrapper.setReturnFormat( RDF )
results = sparql_wrapper.query().convert()

print(results)
```
**Wherein when specifying formats with 'setReturnFormat' the following formats are working flawlessly:**
`JSON, XML, CSV, TSV`

**The following produce warnings but still produce sensible results:**
`sparql_wrapper.setReturnFormat( TURTLE )` 
returns the warning:
```
/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py:573: RuntimeWarning: Sending Accept header '*/*' because unexpected returned format 'turtle' in a 'SELECT' SPARQL query form
  warnings.warn("Sending Accept header '*/*' because unexpected returned format '%s' in a '%s' SPARQL query form" % (self.returnFormat, self.queryType), RuntimeWarning)
```

`sparql_wrapper.setReturnFormat( RDFXML )` 
returns the warning:
```
/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py:573: RuntimeWarning: Sending Accept header '*/*' because unexpected returned format 'rdf+xml' in a 'SELECT' SPARQL query form
  warnings.warn("Sending Accept header '*/*' because unexpected returned format '%s' in a '%s' SPARQL query form" % (self.returnFormat, self.queryType), RuntimeWarning)
/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py:847: RuntimeWarning: Format requested was RDF+XML, but XML (application/sparql-results+xml; charset=UTF-8) has been returned by the endpoint
  warnings.warn(message % (requested.upper(), format_name, mime), RuntimeWarning)
```

**And the RDF-format returns errors and no sensible results:**
`sparql_wrapper.setReturnFormat( RDF )`
returns error:
```
/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py:573: RuntimeWarning: Sending Accept header '*/*' because unexpected returned format 'rdf' in a 'SELECT' SPARQL query form
  warnings.warn("Sending Accept header '*/*' because unexpected returned format '%s' in a '%s' SPARQL query form" % (self.returnFormat, self.queryType), RuntimeWarning)
Traceback (most recent call last):
  File "a_queryPy.py", line 9, in <module>
    results = sparql_wrapper.query().convert()
  File "/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py", line 864, in convert
    return self._convertRDF()
  File "/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py", line 787, in _convertRDF
    retval.load(self.response) # (DEPRECATED) publicID=' ')
  File "/usr/local/lib/python3.5/dist-packages/rdflib/graph.py", line 1050, in load
    self.parse(source, publicID, format)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/graph.py", line 1496, in parse
    context.parse(source, publicID=publicID, format=format, **args)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugins/parsers/rdfxml.py", line 578, in parse
    self._parser.parse(source)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.5/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 468, in EndElement
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 370, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugins/parsers/rdfxml.py", line 160, in endElementNS
    self.current.end(name, qname)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugins/parsers/rdfxml.py", line 332, in node_element_end
    self.error("Repeat node-elements inside property elements: %s"%"".join(name))
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugins/parsers/rdfxml.py", line 186, in error
    raise ParserError(info + message)
rdflib.exceptions.ParserError: None:6:164: Repeat node-elements inside property elements: http://www.w3.org/2005/sparql-results#binding
```

The last one looks like it could be caused by issues of different RDF serializitations (https://stackoverflow.com/questions/27243394/rdflib-repeat-node-elements-parse-error-with-owl-xml-file) but I couldn't resolve it in this way. 

What I find suspicous is this warning 'RuntimeWarning: Sending Accept header' regarding which I couldn't find any helpful information so far. Is it related to format RDF not producing results at all? And / or what does it mean in general and how can I avoid it?

Cheers!

**Comment by dayures** [comment]
Dear all,

The behaviour that it is described is the intended one for TURTLE and RDFXML.

From https://www.w3.org/TR/sparql11-protocol/#query-success :

> The response body of a successful query operation with a 2XX response is either:
> * SELECT and ASK: a SPARQL Results Document in XML, JSON, or CSV/TSV format.
> * DESCRIBE and CONSTRUCT: an RDF graph serialized, for example, in the RDF/XML syntax, or an equivalent RDF graph serialization.

So it is not expected that a RDF/XML or TURTLE format for a SELECT query type. That's why these warning messages are shown.

For the latest case (error in SELECT with RDF return format), I will need to digg more inside it.

@steffres which version of SparqlWrapper are you using? I am assuming that you are using Python 3.5

**Comment by steffres** [comment]
Hi @dayures !

Thanks for your answer. Regarding RDF/XML and TURTLE I will ignore those warnings then?

And as for the versions:
`pip3 show SPARQLWrapper`
returns Version: 1.8.1

and python is 3.5.2

**Comment by dayures** [comment]
@steffres yes, you could ignore the warnings for `RDF/XML` and `TURTLE` (there are just warnings), but remember the specification :)

The case of `RDF` is similar to the previous one. It is not intended to return a RDF graph if a SELECT or ASK query type has been queried. Just in case, if you want that the SPARQL endpoint returns results in "SPARQL Query Results XML Format" https://www.w3.org/TR/rdf-sparql-XMLres/ , set the return format to `XML` (`sparql_wrapper.setReturnFormat(XML)`).

Regarding the error, I was able to reproduce it in my environment. And the error is coming from the "convert" part. It looks like the returned value from dbpedia endpoint is not a valid RDF.

If you go to dbpedia endpoint frontend (http://dbpedia.org/sparql), and test the query  with `RDF/XML` as results format, you will obtain a `sparql.rdf` file, a supposed valid RDF/XML file. If you try to validate it against a validator, you will receive an error (I have tested it using some online applications, like http://www.easyrdf.org/converter, and also using `rdflib` parse capabilities).

**Comment by steffres** [comment]
Yeah, so far we've mostly used xml instead. As for the specifications, thanks for your pointers, I'll keep them in mind.

As for the RDF/XML file, our endpoint also returns invalid RDF/XML files, if you want you can check this by executing the query
`select distinct ?Concept where {[] a ?Concept} LIMIT 10`
here at https://virtuoso.parthenos.d4science.org/sparql .
So do I understand this correctly then, that this seems to be an issue due to virtuoso, the underlying triplestore in general?

**Comment by dayures** [comment]
That's could be a possibility. 

@steffres do you think that this issue can be closed?

**Comment by steffres** [comment]
Sorry, forgot; I do close it now. 
Thank you for your support!

**Comment by dayures** [comment]
@steffres  thanks for providing feedback!
