### ISSUE TITLE
Using SPARQL Wrapper with RDFLIB and Python3 references urllib2

### ISSUE THREAD

**Issue by fcbr** [RDFLib/sparqlwrapper#109]
Hi,

```
$ pip3 list
rdflib        4.2.2    
SPARQLWrapper 1.8.1    
urllib3       1.22     
```

The following code gives me an exception trying to reference `urllib2`, which doesn't exist anymore in Python3.

```python
g = ConjunctiveGraph(store=SPARQLStore(url))
```

```shell
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    ConjunctiveGraph(store=SPARQLStore('xxx'))
  File "/Users/fchalub/w/work/notebook/env/lib/python3.6/site-packages/rdflib/plugins/stores/sparqlstore.py", line 232, in __init__
    self.setUseKeepAlive()
  File "/Users/fchalub/w/work/notebook/env/lib/python3.6/site-packages/SPARQLWrapper/Wrapper.py", line 502, in setUseKeepAlive
    if urllib2._opener and any(isinstance(h, HTTPHandler) for h in urllib2._opener.handlers):
NameError: name 'urllib2' is not defined
```

**Comment by dayures** [comment]
@wikier It looks like this issue is related to this line somehow related to keepalive (and urllib2) https://github.com/RDFLib/sparqlwrapper/blob/3dd4d468674ca9767b93ae33f2a3cff3a916c42d/SPARQLWrapper/Wrapper.py#L587
any ideas to solve it?

**Comment by wikier** [comment]
Most-likely... I'll take a look during the weekend.

**Comment by mbarann** [comment]
I have the same problem with Python 3. I think the problem is that the 2to3 step, which is run during the installation of SPARQLWrapper package, does not adapt this Python 2 code correctly. 

Maybe six.moves.urllib instead of urllib2 can be used to fix this, then 2to3 does not have to adapt this.

It would be nice if this can be fixed, otherwise SPARQLWrapper cannot be used with keepalive in Python 3.

**Comment by dayures** [comment]
The dependency that caused the issue was remove on rdflib (see https://github.com/RDFLib/rdflib/commit/7255e6db12e6479d10b3b738fef1529e393c9ff7). But as far as there is no new release of rdflib since 4.4.2 (dependency of SPARQLWrapper), this issue would raise.

**Comment by dayures** [comment]
A new release of SPARQLWrapper (1.8.3) has just been launched and it is ready to be used (and hopefully, with this issues solved). https://pypi.org/project/SPARQLWrapper/1.8.3/#files
