### ISSUE TITLE
setup.py imports SPARQLWrapper before install_requires can be run

### ISSUE THREAD

**Issue by cottrell** [RDFLib/sparqlwrapper#113]
Not a huge deal but everyone will hit this if they import mods specified in install_requires I think.

See note here:

https://github.com/RDFLib/sparqlwrapper/pull/86

**Comment by dayures** [comment]
@cottrell What do you think to use something like https://gist.github.com/techtonik/4066623 in order to remove the `import `?

**Comment by cottrell** [comment]
Seems reasonable ... Doing this kind of thing is really just trying to hook
into a convention as far as I can tell. If there is some way of changing
the convention to make this stuff easier that might be better. Whatever is
easiest and simplest and doesn't confuse future people too much.

**Comment by dayures** [comment]
@cottrell maybe there are better solutions, but I didn't find them. Do you have any suggestion?

**Comment by dayures** [comment]
from PEP 396 -- Module Version Numbers specification:

> The version attribute in a classic distutils setup.py file, or the PEP 345 Version metadata field SHOULD be derived from the __version__ field, or vice versa.
