### ISSUE TITLE
setQuery() very slow for queries with WITH <graph>

### ISSUE THREAD

**Issue by VulumeCode** [RDFLib/sparqlwrapper#120]
The regex in `sparql.pattern.search(query).group("queryType").upper()` is slow for queries with a `WITH` clause, and VERY slow for queries with  both a `WITH` clause and leading spaces.

On my machine it takes about 10 seconds for long-ish query with a dozen prefixes. Without leading spaces it takes 3ms. Without `WITH` it takes 30µs (leading spaces or not). 

`sparql.pattern` should be modified to take `WITH` in account, as it is valid SPARQL 1.1. Possibly other keywords which can be used here (like `FROM`) can cause issues as well.

**Comment by dayures** [comment]
thanks for your comment. In some initial testing, it looks like that a long list of prefixes slow down all the process. 

@VulumeCode did you try the same query without prefixes? Could you share some examples in order to prepare some tests?

**Comment by VulumeCode** [comment]
I need the prefixes. I can do without `WITH` by setting the default graph. 
It does indeed only seem to happen if there's also some prefixes. 

```
# 10 sec
q = """
    PREFIX a: <http://dbpedia.org/a>
    PREFIX b: <http://dbpedia.org/b>
    PREFIX c: <http://dbpedia.org/c>
    PREFIX d: <http://dbpedia.org/d>
    PREFIX e: <http://dbpedia.org/e>
    PREFIX f: <http://dbpedia.org/f>
    PREFIX g: <http://dbpedia.org/g>
    PREFIX h: <http://dbpedia.org/h>
    WITH <http://dbpedia.org>
    SELECT ?s ?p ?o WHERE {
        ?s ?p ?o.
    }"""

# 3 sec
q = """PREFIX a: <http://dbpedia.org/a>
    PREFIX b: <http://dbpedia.org/b>
    PREFIX c: <http://dbpedia.org/c>
    PREFIX d: <http://dbpedia.org/d>
    PREFIX e: <http://dbpedia.org/e>
    PREFIX f: <http://dbpedia.org/f>
    PREFIX g: <http://dbpedia.org/g>
    PREFIX h: <http://dbpedia.org/h>
    WITH <http://dbpedia.org>
    SELECT ?s ?p ?o WHERE {
        ?s ?p ?o.
    }"""

# 3 ms
q = """PREFIX a: <http://dbpedia.org/a>
PREFIX b: <http://dbpedia.org/b>
PREFIX c: <http://dbpedia.org/c>
PREFIX d: <http://dbpedia.org/d>
PREFIX e: <http://dbpedia.org/e>
PREFIX f: <http://dbpedia.org/f>
PREFIX g: <http://dbpedia.org/g>
PREFIX h: <http://dbpedia.org/h>
WITH <http://dbpedia.org>
SELECT ?s ?p ?o WHERE {
    ?s ?p ?o.
}"""

# 30 µs
q = """PREFIX a: <http://dbpedia.org/a>
PREFIX b: <http://dbpedia.org/b>
PREFIX c: <http://dbpedia.org/c>
PREFIX d: <http://dbpedia.org/d>
PREFIX e: <http://dbpedia.org/e>
PREFIX f: <http://dbpedia.org/f>
PREFIX g: <http://dbpedia.org/g>
PREFIX h: <http://dbpedia.org/h>
SELECT ?s ?p ?o WHERE {
    ?s ?p ?o.
}"""

# 30 µs
q = """
    PREFIX a: <http://dbpedia.org/a>
    PREFIX b: <http://dbpedia.org/b>
    PREFIX c: <http://dbpedia.org/c>
    PREFIX d: <http://dbpedia.org/d>
    PREFIX e: <http://dbpedia.org/e>
    PREFIX f: <http://dbpedia.org/f>
    PREFIX g: <http://dbpedia.org/g>
    PREFIX h: <http://dbpedia.org/h>
    SELECT ?s ?p ?o WHERE {
        ?s ?p ?o.
    }"""

# 30 µs
q = """
    WITH <http://dbpedia.org>
    SELECT ?s ?p ?o WHERE {
        ?s ?p ?o.
    }"""
```

**Comment by dayures** [comment]
Thanks for the queries! It were very useful for make some testing (you were completely right about the times!).

Just a side comment: Checking the spec (https://www.w3.org/TR/sparql11-query/), it looks like the reserved word "WITH" must be used with (not with SELECT). Quite probably you are using another querytype but for testing purposes you send the one with SELECT, no?

**Comment by VulumeCode** [comment]
I see, yes. Virtuoso allows WITH to be used to choose the graph in SELECT queries as well so I was using that for everything. But this improvement ought to work for all implementations, so great!
