### ISSUE TITLE
can readme.md have a demo about SPARQL update , not just only SPARQL select?

### ISSUE THREAD

**Issue by scil** [RDFLib/sparqlwrapper#121]
I tried update and failed, so hope there are some examples

**Comment by dayures** [comment]
Thanks for your comment and feedback. I am going to prepare a couple of examples (INSERT, DELETE). Hopefully, the library will be fined tuned for SPARQL Update operations. Any suggestion/comment?

**Comment by gpotdevin** [comment]
Landing here after trying to do exactly this but failing.

I am trying to update a named graph using a series of triples which are currently stored in some rdflib graph. 

I guess yet another example (so on top of the example_insert.py you nicely uploaded) demonstrating how to automate this process from one or another triples container (i.e. a rdflib graph, or a list of tupples, or whatever you think is most appropriate) would be awesome.

**Comment by dayures** [comment]
@gpotdevin 

I have prepared a really quick script that probably will not cover all cases. Let me know if this is useful for your purpouses.

```
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDFS

g = Graph()
asturias = URIRef("http://dbpedia.org/resource/Asturias")
g.add( (asturias, RDFS.label, Literal('Asturies', lang="ast") ) )
g.add( (asturias, RDFS.label, Literal('Asturias', lang="es") ) )
g.add( (asturias, RDFS.label, Literal('Asturien', lang="de") ) )

###############################################################################
triples = ""
for subject,predicate,obj in g:
    triples = triples + subject.n3() + " " + predicate.n3() + " " + obj.n3() + " . \n"

query = """WITH <http://example.graph>
INSERT {"""+ triples + """}"""
###############################################################################

from SPARQLWrapper import SPARQLWrapper, POST, DIGEST
  
sparql = SPARQLWrapper("https://example.org/sparql-auth")
sparql.setHTTPAuth(DIGEST)
sparql.setCredentials("login", "password")
sparql.setMethod(POST)

results = sparql.query()
print results.response.read()
```

**Comment by gpotdevin** [comment]
Hello @dayures ,

Sorry I was slow at reacting. 
Yes I think this is a good example, which I believe should cover quite a few use cases.

Thanks a lot for taking the time to write it up !
GP.

**Comment by dayures** [comment]
Added example suggested in the scripts folder (7dc031f2a7cb7adae30ae2b6763569e1bdb591f8)
