### ISSUE TITLE
Create a SPARQL endpoint based on rdflib

### ISSUE THREAD

**Issue by rchateauneu** [RDFLib/sparqlwrapper#128]
Is there a way to create a SPARQL endpoint based on rdflib ?

Something similar to Virtuoso SPARQL query service ( http://vos.openlinksw.com/owiki/wiki/VOS/VOSSparqlProtocol )

**Comment by rchateauneu** [comment]
"This document specifies the SPARQL Protocol; it describes a means for conveying SPARQL queries and updates to a SPARQL processing service and returning the results via HTTP to the entity that requested them."
https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/

**Comment by dayures** [comment]
Hi, I think that this question could be better answered byt the rdflib library team. Let me suggest @rchateauneu to contact the rdflib team https://github.com/RDFLib/rdflib
