### ISSUE TITLE
Wrap multiple endpoints at once

### ISSUE THREAD

**Issue by sharpaper** [RDFLib/sparqlwrapper#134]
Is is possible to wrap more than one sparql endpoint at once? Something like this

        sparql = SPARQLWrapper(["http://host-1.org/sparql", "http://host-2.org/sparql"])

so that I can run a query on a sort of unified graph?

**Comment by dayures** [comment]
Thanks for your question. This is not possible. Maybe you could be interested in [federated queries](https://www.w3.org/TR/sparql11-federated-query/).
