### ISSUE TITLE
automated tests fail, error out

### ISSUE THREAD

**Issue by seth-priya** [RDFLib/sparqlwrapper#148]
I am running inside a container 
# uname -a
Linux 22d64cb76af4 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

using the master branch and following the below steps

git clone --depth=50 --branch=master https://github.com/RDFLib/sparqlwrapper.git
cd sparqlwrapper
python setup.py sdist && pip install ./dist/*
pip install -r requirements.development.txt
pip install rdflib-jsonld
./tests.sh   

The results I get are
----------------------------------------------------------------------
Ran 1307 tests in 13862.259s

FAILED (SKIP=384, errors=163, failures=56)

I see the Travis job is erroring out as well, so can't refer to it, is there anything I am missing here?

Thanks in advance for the help  and support!!

**Comment by dayures** [comment]
Hi @seth-priya 

Thanks for your message.

Could you share the output of the test.sh run (in order to see what were the errors...)?

Sometimes, the issue is the availability (could be down) of the sparql endpoints that are used for the testing.

**Comment by nicholascar** [comment]
We've recently fixed some of the tests that were failing in Travis so please re-test with updated code from the `master` branch.

**Comment by seth-priya** [comment]
Thanks, all tests pass now!!
