### ISSUE TITLE
manage long results

### ISSUE THREAD

**Issue by mfarre** [RDFLib/sparqlwrapper#48]
Hello,

Every query I do is trunkated to 100 results (currently using sparqlwrapper to query an openrdf database). 
Would be great to overcome this, happy to help.

Thanks,
Miquel

**Comment by joernhees** [comment]
this is weird as i'm using it on a daily basis for result sets up to 1M rows...

can you provide some simplistic example showing the bug?

**Comment by mfarre** [comment]
Hello Jörn,

I think the problem is related with the parsing of the results from Sesame/openrdf: by default is truncating the results to 100.

I tried to make this query in the Sesame/openRDF query console:
SELECT ?a 
WHERE { 
?a ?b ?c
}

It generates the following URL: http://localhost:8080/openrdf-workbench/repositories/12345/query?action=exec&queryLn=SPARQL&query=SELECT%20%3Fa%20%0AWHERE%20{%20%0A%3Fa%20%3Fb%20%3Fc%0A}%0A&limit=100&infer=true&

As you can see is adding  &limit=100 that limits the results to 100. Nevertheless, if manually changing limit=100 for limit=0 it returns all the results.

I was wondering if the easiest way to solve this could be to append a limit=0 to the query URL generated by sparqlwrapper.

How do you see that?

**Comment by joernhees** [comment]
uhm, there probably is a way to change the default limit / disable it in your openrdf workbench, but that doesn't seem to be an issue with SPARQLWrapper...

another option could maybe be to explicitly set a limit in the SPARQL Query you're doing?
```sql
select distinct ?s where { ?s ?p ?o } limit 100000000
```

**Comment by mfarre** [comment]
Hey Jörn,
I also thought in trying this before posting here and it doesn't work: is limiting the number of results to 100000000 but still truncating the number of results to 100 per page. Then (I guess) when the scrapping is done, the sparqlwrapper only have 100 results there.

I have solved the problem adding the limit=0 in the request URL, to do this I use the addParameter(key,value) function:
	sparql = SPARQLWrapper("http://localhost:8080/openrdf-workbench/repositories/12345/query")
	sparql.addParameter('limit','0')

Thanks for your time, hope it helps somebody else in the future!

**Comment by joernhees** [comment]
:+1:

**Comment by wikier** [comment]
:+1: 

I was not aware either of such default limit from workbench's endpoint. Try to ask at [sesame-users](https://groups.google.com/d/forum/sesame-users) if such configuration can be changed or disabled.
