### ISSUE TITLE
SmartWrapper.Value should have __repr__

### ISSUE THREAD

**Issue by keturn** [RDFLib/sparqlwrapper#49]
When using the SmartWrapper, I found it discouraging to get output that looked like this:

    >>> results.bindings
    [{u'o': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f610>,
      u'p': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f5d0>,
      u's': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f550>},
     {u'o': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f6d0>,
      u'p': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f690>,
      u's': <SPARQLWrapper.SmartWrapper.Value at 0x106b6f650>}]

Defining `__repr__` on `SmartWrapper.Value` helps a lot. Here's one implementation:

    def __repr__(self):
        cls = self.__class__.__name__
        return "%s(%s:%r)" % (cls, self.type, self.value)

which provides enough transparency to see what the underlying value is but still makes it clear that you're looking at a wrapped Value.

**Comment by joernhees** [comment]
:+1: if you make a PR i guess it will be accepted.

**Comment by wikier** [comment]
thanks for the patch, @keturn!
