### ISSUE TITLE
allow for manual setting of Accept header or headers in general

### ISSUE THREAD

**Issue by joernhees** [RDFLib/sparqlwrapper#52]
as can be seen in http://stackoverflow.com/a/30306013/1423333 there are endpoints out there which don't understand the `",".join(_SPARQL_JSON)` https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L451 Accept header, but only want "one" mime-type :(

in https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L506 we unconditionally add the Accept header.

I think it would be much better if one could manually set headers somehow and the `_createRequest()` method wouldn't override them if they're there already.

Could be done in one go when switching to the Requests lib (see #51)?

**Comment by wikier** [comment]
Well, I understand the feature request. 

But... the issue is clearly server-side. The idea is to stay bound to the [protocol](http://www.w3.org/TR/sparql11-protocol/). Small changes for a broader support are fine. But we should put a line where we do not support such wrong behaviors.  

What do others (@iherman, @indeyets, @dayures, etc) think?

**Comment by joernhees** [comment]
i didn't want to suggest to encourage bad behavior, but i'm suggesting to allow for easier customization so that developers can use the lib in the real world even if things go slightly wrong.

If you read the thread on stackoverflow, you saw that the endpoint actually follows protocol, but that it doesn't seem to understand the longer than necessary Accept header we send for compatibility reasons: `Accept: application/sparql-results+json,text/javascript,application/json`. The endpoint doesn't understand the `,` joined alternatives, but it would understand `Accept:  application/sparql-results+json`.

Why shouldn't we allow a developer to just send one of these alternatives / in general manually set the headers?

At the moment the workaround for this really minor flaw of the endpoint is relatively complicated just cause `_createRequest()` does it in-line (so it doesn't call another method one could override) and it doesn't check if that header was already set.

**Comment by psychemedia** [comment]
I need to access an endpoint that requires a custom header attribute to pass an API token.

Am I correct in thinking that I *can't* do this with SPARQLwrapper as it currently stands?

**Comment by wikier** [comment]
@psychemedia, do you need header or parameter?

Because for parameter `SPARQLWrapper` provides something https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L318

But headers we're not yet there.

**Comment by psychemedia** [comment]
Header.... 

I wondered about something hacky like adding a parameter into class initialiser:

```
  def __init__(self, endpoint, updateEndpoint=None, returnFormat=XML, defaultGraph=None, agent=__agent__, extraheaders=None):

  ...
    self.extraheaders = extraheaders if extraheaders else {}
```

and then fudging the request code:

```
    def _createRequest(self):
        ...
        for extraheader in self.extraheaders:
            request.add_header(extraheader, self.extraheaders[extraheader])
 ```

**Comment by dayures** [comment]
@wikier @iherman @indeyets What do you think to add the functionality explained in https://github.com/RDFLib/sparqlwrapper/issues/52#issuecomment-326627663 ?

**Comment by wikier** [comment]
SGTM

**Comment by dayures** [comment]
See pull request #103 with an initial approach
