### ISSUE TITLE
travis tests fail for py3

### ISSUE THREAD

**Issue by joernhees** [RDFLib/sparqlwrapper#57]
tests for python 3 seem to fail somewhere around the urlgrabber module:

https://travis-ci.org/RDFLib/sparqlwrapper/jobs/77481345

**Comment by wikier** [comment]
fixed! 

see https://travis-ci.org/RDFLib/sparqlwrapper/builds/88288324 for instance

**Comment by joernhees** [comment]
thanks for fixing this, but can you elaborate on where it is needed anyhow?

seems to me that urlgrabber was only used for keepalive:
https://github.com/RDFLib/sparqlwrapper/blob/e9216658f47d48ec983b2f8153e9d73e3d4f5a87/SPARQLWrapper/Wrapper.py#L403

maybe it would be better not to depend on anything here at all?

**Comment by joernhees** [comment]
closing in favor of #63

**Comment by wikier** [comment]
well, I realized `pycurl` was a high-level dependency to `urlgrabber`, better managed in python 3.x

so I though was the best solution, but let's discuss it in issue #63
