### ISSUE TITLE
New error in existing notebook

### ISSUE THREAD

**Issue by alberto-ieru** [RDFLib/sparqlwrapper#61]
Hello,
I developed a notebook six months ago and it was working perfectly. Yesterday I have to run it again, getting this error.

QueryBadFormed: QueryBadFormed: a bad request has been sent to the endpoint, probably the sparql query is bad formed. 

Response:
Could not properly handle &quot;PREFIX rdf%3A %3Chttp%3A//www.&quot; in ARC2_SPARQLPlusParser

Heres is the code:

```python
prefixes = """PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX dc: <http://purl.org/dc/terms/> 
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
PREFIX dcat-ext: <http://vocabularies.aginfra.eu/dcatext#> 
PREFIX schema: <http://schema.org/>"""

endpoint = "http://ring.ciard.net/sparql1" #put your endpoint here

sparql = SPARQLWrapper2(endpoint)

sparql.setQuery(prefixes + """
SELECT ?dataset ?description
WHERE {
    ?dataset rdf:type dcat:Dataset .
    ?dataset dc:description ?description .
} 
""")

#sparql.setReturnFormat(JSON)
ret = sparql.query()
```

Thanks a lot

**Comment by joernhees** [comment]
i assume you're talking about an ipython notebook...

the error-message you get is originating from the server, so i'd recommend checking if it was updated in between, it's still responding, etc...

i'll close this for now, feel free to reopen if you find this is an actual problem in SPARQLWrapper
