### ISSUE TITLE
Error install pycurl dependency

### ISSUE THREAD

**Issue by mwjackson** [RDFLib/sparqlwrapper#63]
We are seeing this error in our deployments as of a few hours ago (~ 1.7.1 release). Pinning SPARQLWrapper==1.6.4 resolves the problem. We are running python 2.7 and latest rdflib.

Collecting pycurl>=7.19.5.1 (from SPARQLWrapper->rdflib->-r requirements.txt (line 1))
  Using cached pycurl-7.19.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-2nJEva/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/tmp/pip-build-2nJEva/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/tmp/pip-build-2nJEva/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/tmp/pip-build-2nJEva/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

**Comment by joernhees** [comment]
hmm, seems to me that pycurl (which was introduced in https://github.com/RDFLib/sparqlwrapper/commit/5d691cc78f07ef9b9b80fd4b3f087a7273d446e5 as replacement for urlgrabber ) is never used in the SPARQLWrapper code...

as mentioned in #57 it's maybe best if we just remove urlgrabber and don't add a new dependency?

**Comment by mbarrien** [comment]
Note that http://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing suggests a system library may need to be installed to resolve this issue.

That said, if it's not used, dropping the requirement sounds good.

**Comment by wikier** [comment]
I introduced the dependency to `pycurl` to solve the issue we had with `urlgrabber` in Python 3.x.

Said that, we're discussion here two things:

1. Why @mwjackson can fetch [pycurl 7.19.5.1](https://pypi.python.org/pypi/pycurl/7.19.5.1) from pypy? Could be a temporal issue? For me worked fine, also for our [CI builds](https://travis-ci.org/RDFLib/sparqlwrapper/builds)...
2. The question @joernhees asks is about removing `urlgrabber` (or `pycurl`) as dependency in the code. I'd love to. So, could you please provide a PR for keeping the support for keepalive without using it?

**Comment by cwacekINV** [comment]
FWIW adding the pycurl dependency breaks pip installs on Windows, because pycurl doesn't have built in support for Windows (pycurl/pycurl#297). This is more problematic than for linux because there's no easy way to get libcurl installed. 

Since SPARQLWrapper is a dependency of rdflib, this breaks rdflib installs on Windows.

**Comment by wikier** [comment]
Ummm... then we have a problem. Sorry for that, but non of our developers or our continuous integration works under Windows.

Then I'll take a look to issue #51 to see how I can sort this out.

**Comment by wikier** [comment]
@mwjackson 1.7.2 is now available with a hotfix for this issue https://pypi.python.org/pypi/SPARQLWrapper/1.7.2 please check it

**Comment by mwjackson** [comment]
thanks guys, works... appreciated

**Comment by joernhees** [comment]
@wikier thanks for fighting through this ;)
