### ISSUE TITLE
Link for rdflib raises Error

### ISSUE THREAD

**Issue by trishnaguha** [RDFLib/sparqlwrapper#64]
The link for rdflib "http://www.rdflib.net/" in http://rdflib.github.io/sparqlwrapper gives "Error:not found" . It should be changed to https://pypi.python.org/pypi/rdflib

**Comment by dayures** [comment]
Maybe the links could be:
- https://pypi.python.org/pypi/simplejson
- https://pypi.python.org/pypi/rdflib

**Comment by trishnaguha** [comment]
Thanks! :)
