### ISSUE TITLE
query type detection does not work with non-newline queries

### ISSUE THREAD

**Issue by vtermanis** [RDFLib/sparqlwrapper#74]
Unfortunately the pattern to remove single-line comments (introduced in issue #32) causes single-line queries' type to not be recognised. E.g. if one has the query

```
prefix whatever: <http://example.org/blah#> ASK { ... }
```

.. then the `"#.*?\n"` pattern used (to remove comments in `_parseQueryType`) prunes the query to:

```
prefix whatever: <http://example.org/blah#
```

(Off topic: We strip newlines & indentation whitespace before passing to sparqlwrapper so that Fuseki server query log output stays sane and to reduce overall query size.)

**Comment by vtermanis** [comment]
This might do the trick (to remove single line comments):
```python
re.compile(r"""
    \n
    # bits of query
    (?P<query_parts>(
        # IRI
        <.*?>|
        # quoted strings
        ".*?"|
        # everything except starts for the above two whitespace and comment
        [^<"\#\s]+|
        # whitespace (apart from newline)
        [^\S\n]+
    # bits of query can have zero or more elements
    )*)
    # comment (up to next newline, if present)
    (\s*\#.*)?(?![^\n])""", re.X)
```
(It might not be necessary to check whether the whole match starts & ends with newline - I'm not sure.)

**Comment by joernhees** [comment]
hmm, while this seems to solve the comment problem, in #32 @gromgull already mentioned that it could be beneficial to use the rdflib sparql parser to do this properly... i'd actually vote for that as it reduces code-duplication for partial parsing with weird side effects like this...

**Comment by vtermanis** [comment]
The only downside might be (although maybe I'm wrong?) that it's considerably less efficient to ask rdflib to parse it first (assuming regex uses C extension). Wouldn't it be better to rely on the user to indicate whether they're trying to perform a query or update request? After all, they must know what they're doing in order to do something with (or the lack of) response data from the request anyway. I do realise this would break backwards compatibility so presumably is out of the question.
(Whilst e.g. SQL libraries have a single query() function, they still assume the user to know what they're doing with what comes back.)

**Comment by vtermanis** [comment]
One last thought: How about if query() allows one to specify whether it's a _query_ or an _update_ request but make the parameter optional (and, if not specified, check query for type as before).
