### ISSUE TITLE
test fails under py3 due to urllib

### ISSUE THREAD

**Issue by ignatenkobrain** [RDFLib/sparqlwrapper#81]
basically `urllib._opener` doesn't exist on py3.

**Comment by ignatenkobrain** [comment]
`find -type f -name '*.py' -exec sed -i -e 's/urllib2._opener/urllib.request._opener/g' {} ';'` fixes.

**Comment by joernhees** [comment]
how did you install this? isn't this caught by 2to3?

**Comment by ignatenkobrain** [comment]
looks like private methods are not covered by 2to3

**Comment by joernhees** [comment]
seems tests should be run with https://github.com/RDFLib/sparqlwrapper/blob/master/tests.sh which does exactly what you suggest to the test that fails. This will probably get an overhaul after rdflib 5.0.0 anyhow and be converted to six as well (so it doesn't need 2to3 anymore at all).

I'll close this for now, reopen if you can think of an easy better solution.
