### ISSUE TITLE
return format setting does not work with MarkLogic SPARQL endpoint

### ISSUE THREAD

**Issue by zednis** [RDFLib/sparqlwrapper#82]
The Marklogic REST API SPARQL Endpoint implementation (https://docs.marklogic.com/REST/GET/v1/graphs/sparql) returns an error if passed query parameters it does not recognize:

GET request URL:
```http://localhost:8060/v1/graphs/sparql?query=SELECT+%2A+WHERE+%7B+%3Fs+%3Fp+%3Fo+%7D&results=json&format=json&output=json'```

response:
```
{"errorResponse":{"statusCode":400, "status":"Bad Request", "messageCode":"REST-UNSUPPORTEDPARAM", "message":"REST-UNSUPPORTEDPARAM: (err:FOER0000) Endpoint does not support query parameter: invalid parameters: results, output for request"}}
```
Looking into Wrapper.py it seems that all plausible output format query parameters are sent for every request.

Wrapper.py:109

```python
# This is very ugly. The fact is that the key for the choice of the output format is not defined. 
# Virtuoso uses 'format', joseki uses 'output', rasqual seems to use "results", etc. Lee Feigenbaum 
# told me that virtuoso also understand 'output' these days, so I removed 'format'. I do not have 
# info about the others yet, ie, for the time being I keep the general mechanism. Hopefully, in a 
# future release, I can get rid of that. However, these processors are (hopefully) oblivious to the 
# parameters they do not understand. So: just repeat all possibilities in the final URI. UGLY!!!!!!!
_returnFormatSetting = ["format", "output", "results"]
```

Would it be possible to let the client specify what which output query parameter to use?  Also, perhaps to not use any output query parameters if the client wishes to use content negotiation instead?

**Comment by joernhees** [comment]
related: #37, #52

i fully agree that this is ugly :-/

for now a quick fix would be to monkey-patch the `_returnFormatSetting` var from your code:
```python
import SPARQLWrapper.Wrapper
SPARQLWrapper.Wrapper._returnFormatSetting = []
```

**Comment by zednis** [comment]
That works!  Thanks.

**Comment by dayures** [comment]
@joernhees @zednis This request has been added (partially) in the code.
BTW, Do you know any public Marklogic SPARQL Endpoint in order to create a suite of tests for it ?

**Comment by zednis** [comment]
@dayures sadly, I do not.
