### ISSUE TITLE
urllib2.HTTPError: HTTP Error 414: Request-URI Too Large

### ISSUE THREAD

**Issue by mit2nil** [RDFLib/sparqlwrapper#83]
Hi Dev,

Is there a way to support large SPARQL queries?

I am getting HTTP error 414 when using long query through SPARQLWrapper

Nilay

**Comment by mit2nil** [comment]
Using sparqlwrapper version 1.8.0 on python 2.7.X on Windows 10 machine. Below is the error stack

```
Traceback (most recent call last):
  File "sparql.py", line 9, in <module>
    results = sparql.query().convert()
  File "C:\stuff\Git\museum-link-curation\pyenv\lib\site-packages\SPARQLWrapper\Wrapper.py", line 601, in query
    return QueryResult(self._query())
  File "C:\stuff\Git\museum-link-curation\pyenv\lib\site-packages\SPARQLWrapper\Wrapper.py", line 581, in _query
    raise e
urllib2.HTTPError: HTTP Error 414: Request-URI Too Large
```

**Comment by joernhees** [comment]
you could try setting the request method to POST...
`sparql.setRequestMethod('POST')` before query

**Comment by mit2nil** [comment]
@joernhees I tried adding that but still getting the same error. 
Also based on the documentation here https://rdflib.github.io/sparqlwrapper/doc/latest/, I thought by default POST is used. Either way, I tried adding the line you suggested but I am getting below warning.
`C:\stuff\Git\linking\pyenv\lib\site-packages\SPARQLWrapper\Wrapper.py:261: RuntimeWarning: invalid update method 'post'
  warnings.warn("invalid update method '%s'" % method, RuntimeWarning)`

I looked at the source code and it only supports two values 
`# Possible methods to perform requests
URLENCODED = "urlencoded"
POSTDIRECTLY = "postdirectly"
_REQUEST_METHODS  = [URLENCODED, POSTDIRECTLY]`

I tried both of them and both are still throwing HTTP 414

**Comment by CameronJRAllan** [comment]
I am experiencing the same issue with large queries, using either URLENCODED or POSTDIRECTLY.

"urllib.error.HTTPError: HTTP Error 414: Request-URI Too Large"

**Comment by CameronJRAllan** [comment]
Upon further inspection, the condition "if self.method == POST:" is never found to be true, which is causing the issue.

Reference:
Line 527, Wrapper.py

Could this be due to self.method not being set correctly and hence defaulting to GET?

**Comment by CameronJRAllan** [comment]
To fix this issue, ensure that your method is set correctly, e.g:
    _self.sparql.setRequestMethod(POSTDIRECTLY)
    self.sparql.setMethod("POST")__

**Comment by dayures** [comment]
@mit2nil @CameronJRAllan  could you provide more details (public SPARQL endpoint + query) about this issue?

**Comment by dayures** [comment]
Thanks for contributing to this issue. As it has been more than 90 days since the last activity, we are automatically closing the issue. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this issue or open a new one. We'll gladly take a look again!
